### ISSUE TITLE
Allow volume control via scrolling - Feature request

### ISSUE THREAD

**Issue by gevera** [mate-desktop/mate-indicator-applet#12]
In most modern desktops it is possible to control the audio volume output by hovering over the audio icon in the panel and just scrolling up or down. It is simple and convenient way of audio volume control.
Unfortunately MATE indicator applet doesn't support this feature just yet.

**Comment by monsta** [comment]
MATE's indicator applet is just a container. This is probably should be reported at LP [here](https://launchpad.net/ubuntu/+source/indicator-application-gtk2/+bugs) or [here](https://bugs.launchpad.net/indicators-gtk2).
