### ISSUE TITLE
mate-indicator-applet should provide a replacement for indicator-messages

### ISSUE THREAD

**Issue by marmistrz** [mate-desktop/mate-indicator-applet#13]
The packaging recommends `indicator-messages-gtk2`. The package is not installable though. MATE should provide such package because the functionality of this applet cannot be achieved in another way, AFAIK.

**Comment by monsta** [comment]
Do you use Debian with ```--install-recommends``` enabled (IIRC it's the default there)?

**Comment by monsta** [comment]
Anyway, the latest version doesn't recommend that package anymore.
