### ISSUE TITLE
mate-indicator-applet should notify about missed notifications

### ISSUE THREAD

**Issue by marmistrz** [mate-desktop/mate-indicator-applet#14]
In Cinnamon if a notification is not reacted to, the notifications area shows an exclamation mark to indicate that some notifications have been missed. MATE lacks this functionality.

**Comment by monsta** [comment]
How is that related to indicator-applet? Notification area and indicator applet area are different places.

**Comment by marmistrz** [comment]
https://github.com/linuxmint/mate-packages/blob/master/mate-indicator-applet/debian/control#L25

Plus
```
$ sudo apt-get install indicator-messages-gtk2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package indicator-messages-gtk2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'indicator-messages-gtk2' has no installation candidate
```

**Comment by monsta** [comment]
Never tried that package, but it seems to me that it collects only messages from various internet messengers in one place, not desktop notifications. Anyway, indicator-applet is just a container, we can't change the applets themselves (which are made mostly by Canonical for Ubuntu).

**Comment by marmistrz** [comment]
Yes, but indicator-messages is done by Canonical and installable but not detected by MATE. indicator-messages-gtk2 is no more in the repos.

**Comment by Exalm** [comment]
indicator-message, as all other Ubuntu indicators, use GTK3. mate-indicator-applet, as mate-panel, uses GTK2. Indicators used to use GTK2 in older versions, but are discontinued and are being phased out. The only ways now are to either port entire mate-panel to GTK3 or to embed GTK3 indicators into GTK2 panel. (xfce4-indicator-applet does this somehow)

**Comment by monsta** [comment]
Yes, and there's a feature request (https://github.com/mate-desktop/mate-indicator-applet/issues/8) about supporting GTK+3 indicators.

I highly doubt we will fork any more packages - we don't really have enough manpower to support them.
Cinnamon gets more developers every year, we don't.

Anyway, I'm closing this issue since this is not really about mate-indicator-applet. You can file a feature request in mate-notification-daemon repo if you wish.
