### ISSUE TITLE
 indicator-messages is not shown in mate-panel on Ubuntu 16.04 LTS MATE

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/mate-indicator-applet#20]
it is known that [messaging menu returned in Ubuntu MATE 16.10](https://ubuntu-mate.community/t/messaging-menu-is-making-a-return-in-16-10/7268/9), but there is no such menu in Ubuntu 16.04 LTS MATE even with `ppa:ubuntu-mate-dev/xenial-mate` enabled.

Steps to reproduce:
1. Install Ubuntu 16.04 LTS MATE.
2. Install 'indicator-applet-complete' and 'indicator-messages' packages
3. Add Indicator Applet Complete to the mate-panel.
4. Launch Thunderbird - this should enable Envelope/Letter icon in 'mate-panel' and set corresponding config (check with `dconf read /com/canonical/indicator/messages/applications` = `['thunderbird.desktop']`).

Expected results:
Envelope/Letter ('indicator-messages') icon is shown in 'indicator-applet-complete' inside 'mate-panel' and is usable by Thunderbird or mailnag.

Actual results:
Envelope/Letter ('indicator-messages') is not shown and is not usable.

If it is possible please backport indicator-messages from 16.10 to 16.04 LTS.
I reported [bug 1683516 to the launchpad](https://bugs.launchpad.net/bugs/1683516).

**Comment by flexiondotorg** [comment]
Hi, Ubuntu MATE maintainer here. This is not an issue in upstream MATE. Sorry but we won't be back porting messages-indicator support to 16.04.

**Comment by monsta** [comment]
This isn't possible in GTK+2 build. Support for new style indicators (and indicator-messages is one of them) requires linking to libido3 which is a GTK+3 library. Technical details can be found in https://github.com/mate-desktop/mate-indicator-applet/commit/18ecafbab727d3ccb42254f03db6cff6f6a76850.

**Comment by N0rbert** [comment]
Dear monsta!

I have solved my problem. I was interested in integration of old but functional e-mail checker ([Popper](http://www.omgubuntu.co.uk/2010/09/email-notification-in-ubuntu-popper) from [PPA](https://launchpad.net/~ralf.hersel/+archive/ubuntu/rhersel-ppa)) to the messaging menu of Ubuntu MATE 16.04 LTS. It needs old [`indicator-messages-gtk2`](https://pkgs.org/download/indicator-messages-gtk2).
I [manually installed old packages from Ubuntu 12.04 LTS](https://bugs.launchpad.net/ubuntu/+source/indicator-applet/+bug/1683516/comments/5). 
For now it works and I do not need Gtk+3 messaging menu (I switched back from [MailNag](https://github.com/pulb/mailnag) to Popper).

Thank you!
