### ISSUE TITLE
Typing break indicator is not displayed properly.

### ISSUE THREAD

**Issue by direwolfie** [mate-desktop/mate-indicator-applet#21]
Hi everyone,

Please see below issue.

#### Expected behaviour
Typing break indicator should be displayed properly (please see screenshot of how it looks now).

#### Actual behaviour
Typing break indicator is not displayed properly (first from the left).
![Image of incorrectly displayed typing break indicator](https://user-images.githubusercontent.com/8520837/32413838-650b1f16-c222-11e7-8e19-bc4cec3b6981.png)

#### Steps to reproduce the behaviour

1. Open "Keyboard" preferences window from the Mate menu.
2. Click on "Typing Break" tab.
3. Check the "Lock screen to enforce the typing break" check box.
4. Typing break indicator will appear in the "Indicator applet".

#### MATE general version
1.18.0

#### Package version
mate-applets-1.18.2

#### Linux Distribution
Void Linux

#### Link to downstream report of your Distribution
https://github.com/voidlinux/void-packages/issues/8892

**Comment by monsta** [comment]
This looks more like the tray area. In 1.18 it got StatusNotifier support, so it can display the same indicators as mate-indicator-applet + indicator-application combo.

**Comment by direwolfie** [comment]
Sorry for the late reply.
Do you mean this is from another package?
Please let me know if I should open this issue elsewhere.

**Comment by monsta** [comment]
I don't know yet. Can you check which applet it is?

**Comment by direwolfie** [comment]
It appears in the "Notification Area" applet.
This is the full version and info.
![image](https://user-images.githubusercontent.com/8520837/33038629-f42c5fbc-ce3d-11e7-88da-1b89fcc9bc45.png)

**Comment by direwolfie** [comment]
Hello again :)
Could you please advise if I filed this bug correctly?
If not I will file it elsewhere.

Thanks!

**Comment by lukefromdc** [comment]
Typing break is part of mate-settings-daemon, but failure to properly show a tray or indicator icon is an issue with the tray itself. I do not have the indicator applet installed but do have status-notifier support turned on in mate-panel.

Every time I have tested typing break over the past year it has always rendered correctly. I have, however, seen random icons get partially rendered on occasion(usually they are OK) over the years, a more general bug and a very old one as well.

**Comment by pfalcon** [comment]
Still the issue in Ubuntu MATE 18.04 (MATE 1.20):

Notification Area
1.20.1

Note that this all standard stuff - we (users) don't put anything in "status notifier" or "indicator applet", we just tick a checkbox in keyboard setting, and there it goes like that. (I don't provide screenshot, it looks exactly, pixel-perfect, the same as what @direwolfie posted).

**Comment by pfalcon** [comment]
Btw, everything worked perfectly in Ubuntu MATE 16.04 (MATE 1.16 IIRC).

**Comment by vkareh** [comment]
This was fixed a few weeks ago: https://github.com/mate-desktop/mate-control-center/pull/370
It hasn't been backported to 1.20, as far as I know, but it will definitely be available in the next version of mate.

**Comment by monsta** [comment]
I'm not sure it was what fixed it... I have git master of m-c-c from 10 Jun (haven't updated the branch for months), and I already can't reproduce the issue. I'll investigate more.

**Comment by monsta** [comment]
Ok, this was confusing. I wasn't able to reproduce it on baremetal, but it always happened in VMs with GTK+ 3.22 and 3.24 (and no HiDPI in all cases). I thought it could be a panel issue instead...
So, https://github.com/mate-desktop/mate-control-center/pull/370 actually fixed it. I've picked the commit to 1.20 branch as https://github.com/mate-desktop/mate-control-center/commit/9a36755d9b4cb87011cdbf69c7ac19ff983b43b0.

**Comment by pfalcon** [comment]
@monsta: Thanks for digging to the bottom of it and confirming it's fixed now!
