### ISSUE TITLE
keyboard layout indicator has low contrast on light themes

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/mate-indicator-applet#23]
#### Steps to reproduce:
1. Install Ubuntu 18.04 LTS
2. Install `ubuntu-mate-desktop`
3. Set light theme from `mate-control-center` Appearance - for example darkroom:
![darkroom](https://user-images.githubusercontent.com/309456/34502316-ffb40864-f023-11e7-8ee5-fb1ecf34c154.png)

#### Expected results:
* keyboard layout indicator is visible on light and dark themes

#### Actual results:
* keyboard layout indicator has low contrast on light themes

#### MATE general version
1.18.4

#### Linux Distribution
Ubuntu 18.04 LTS

#### Link to downstream report of your Distribution
Issue filed to the launchpad as [bug 1728711](https://bugs.launchpad.net/bugs/1728711).

**Comment by monsta** [comment]
This is a tray icon, not mate-indicator-applet.

https://github.com/mate-desktop/libmatekbd/issues/28
