### ISSUE TITLE
Request for sound applet

### ISSUE THREAD

**Issue by apolitech** [mate-desktop/mate-indicator-applet#25]
#### Expected behaviour(request-xfce)
![1](https://user-images.githubusercontent.com/14872517/38378667-15fcd2fa-3907-11e8-9a6b-ebfbdb689b5d.png)
![2](https://user-images.githubusercontent.com/14872517/38378672-1815ee82-3907-11e8-955a-8f698baf8df4.png)

#### Actual behaviour
![2](https://user-images.githubusercontent.com/14872517/38379296-ed125f5c-3908-11e8-8456-bfb021fb69a9.png)

#### Steps to reproduce the behaviour
-

#### MATE general version
1.20.0

#### Package version
1.20.0

#### Linux Distribution
Ubuntu Mate

#### Request
It will be nice to have a more powerful applet that allow you to change the input or output on the go and not enter the "Sound settings"

**Comment by flexiondotorg** [comment]
The sound indicator in Ubuntu MATE 18.04 is `indicator-sound` not the MATE sound applet.

Not sure if this bug should remain open here?

**Comment by monsta** [comment]
No, this applet is just a container for various indicators (sound, application, session and so on). Same is Xfce's indicator applet. Maybe they also patched indicator-sound to have additional functionality, I don't know.

**Comment by apolitech** [comment]
Soo where i can make this request?

**Comment by monsta** [comment]
I guess the place for it is https://bugs.launchpad.net/ubuntu/+source/indicator-sound
