### ISSUE TITLE
Network Icon Shows Busy

### ISSUE THREAD

**Issue by selectiveduplicate** [mate-desktop/mate-indicator-applet#26]
I don't know if anyone else is facing this, but I'm having the following issue with the network indicator icon:

![issue](https://user-images.githubusercontent.com/32275394/40446854-70138732-5ef2-11e8-98af-e025be9d4fdb.png)

Most of the times it shows this "busy" condition. It shows busy even if I'm browsing and streaming videos perfectly...

I'm using Ubuntu MATE 18.04.

**Comment by monsta** [comment]
https://launchpad.net/ubuntu/+source/network-manager-applet/+bugs
