### ISSUE TITLE
Indicators freeze on VirtualBox

### ISSUE THREAD

**Issue by anton-z-s** [mate-desktop/mate-indicator-applet#27]
#### Expected behaviour
Indicators should work with VirtualBox VMs focused.

#### Actual behaviour
Indicators freeze when VirtualBox VM is focused and i'm trying to interact with them.

#### Steps to reproduce the behaviour
1. In VirtualBox, start VM.
2. Focus on VM's window.
3. Click on any indicator, whole indicator applet freezes until reboot. 
Same problem with vala-panel-appmenu https://github.com/rilian-la-te/vala-panel-appmenu/issues/238

#### MATE general version
v1.20.1

#### Package version
v1.20.0-1

#### Linux Distribution
Ubuntu Mate 18.04

#### Video driver
```
# lspci -nnk | grep -i vga -A3
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 620 [8086:5916] (rev 02)
	Subsystem: Lenovo HD Graphics 620 [17aa:505b]
	Kernel driver in use: i915
	Kernel modules: i915
```

**Comment by fdbozzo** [comment]
This happens to me too. Ubuntu 18.04 LTS + mate-desktop

Can't click any icon (clicking does nothing) once a VirtualBox VM is opened.

**Comment by flexiondotorg** [comment]
Is this issue still reproducible on VirtualBox? I am unable to reproduce it on hardware or Qemu.

**Comment by anton-z-s** [comment]
Sorry for the delay, I can no longer reproduce the issue.
