### ISSUE TITLE
Where is LINGUAS ?

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-indicator-applet#30]
@flexiondotorg @monsta 
Where is LINGUAS ?
How we add new languages with a translation update?

**Comment by monsta** [comment]
We don't have it in this project. The list of languages is in `configure.ac`. We inherited this from the original indicator-applet.

**Comment by raveit65** [comment]
Hmm, adding by hand without using 'sort' is really ugly. This should be change.

**Comment by raveit65** [comment]
@monsta @flexiondotorg 
There are new releases at pre-release folder. Please test and release.

**Comment by monsta** [comment]
Tested, tagged, moved to release folder. I'll try converting the language list to LINGUAS later.

**Comment by monsta** [comment]
Ok, see https://github.com/mate-desktop/mate-indicator-applet/pull/31.
