### ISSUE TITLE
mate-indicator-applet

### ISSUE THREAD

**Issue by caltrop-3** [mate-desktop/mate-indicator-applet#34]
#### Expected behaviour
i do not know since it does not work

#### Actual behaviour
a skiny vertical line in the panel

#### Steps to reproduce the behaviour
add to panel

#### MATE general version
MATE Desktop Environment 1.18.0

#### Package version
unknown

#### Linux Distribution
linux mint mate 18.2

**Comment by vkareh** [comment]
I don't understand what you mean by "a skinny vertical line in the panel". Do you have a screenshot? Also, can you please report it to the Linux Mint bug tracker and post the link where it says "Link to downstream report..."?

**Comment by lukefromdc** [comment]
Sounds like an icon rendering one line wide.

**Comment by caltrop-3** [comment]
I add it to the panel and there are NO indicators.Just a thin vertical line.There it is in the right monitor under the clock in the white panel - a thin vertical line with NO icons.That's OK, the other standard notification applet is working.

   On Wednesday, August 29, 2018, 11:43:21 PM EDT, Victor Kareh <notifications@github.com> wrote:  
 
 
I don't understand what you mean by "a skinny vertical line in the panel". Do you have a screenshot? Also, can you please report it to the Linux Mint bug tracker and post the link where it says "Link to downstream report..."?

**Comment by lukefromdc** [comment]
That sounds like the entire applet rendering 1px wide or refusing to load any indicators and thus getting a width of zero.  You might try this as a workaround: beginning with mate 1.18, mate-panel supports indicators natively. First, remove the (separate) indicator applet from the panel, then open dconf-editor and go to org>mate>panel>general and make sure enable-sni-support is set to TRUE.  Restart your session (to restart everything creating indicators) and you should see your indicators in the panel itself. Any indicator still giving a 1px wide line is itself at fault. Conversely, if your default new install has both the indicator applet in the panel AND  org>mate>panel>general>enable-sni-support set to TRUE, than you are trying to load the same indicators twice and might be getting a conflict between the panel and the indicator applet as a result. I think that would just show them twice but I do not know as I am on Debian Unstable and only use the panel's native indicator support.

**Comment by scaleoutsean** [comment]
@lukefromdc yep, pixel-wide (indicator) applet (clearly visible in the center of the screen). 
![image](https://user-images.githubusercontent.com/16622642/68182909-cdf4cc00-ffd5-11e9-81cb-de3084c91643.png)
It doesn't look like enabling SNI has helped. It's worked fine for months until some update broke it (same as on older versions - so frustrating). This is Mint 19.2.

**Comment by lukefromdc** [comment]
Assuming you have the tray ("notification area")in the panel, enabling SNI would cause both the panel's own tray and the indicator applet to compete for the same indicators. Workaround is to delete the separate applet from the panel and enable SNI for the tray, then on restarting the panel (or at worst your session to catch all indicators), you should see the indicators in the tray applet

**Comment by scaleoutsean** [comment]
I used to have Indicator Panel but it disappeared. Before enabling SNI I tried to add it back and it was always one pixel wide. 
Yesterday I reset all panels and put everything together, icon by icon... 
It's not the first time this happened, I had the same experience 2-3 times with an earlier version of Mint as well.
