### ISSUE TITLE
No notification from thunderbird

### ISSUE THREAD

**Issue by KarlKnapp** [mate-desktop/mate-indicator-applet#50]
#### Expected behaviour
icon should change color if unread messages are present

#### Actual behaviour
nothing

#### Steps to reproduce the behaviour
receive a new message in thunderbird

#### MATE general version
1.22.2

#### Package version
1.22.1
Thunderbird 68.2.2

#### Linux Distribution
Ubuntu Eoan Ermine

**Comment by slcpunk** [comment]
I can second this - same issue for me.
I tried to use Evolution...but it sucks.  Constantly hangs while composing and slow to update.

**Comment by KarlKnapp** [comment]
Related:   https://bugzilla.mozilla.org/show_bug.cgi?id=1482674

**Comment by KarlKnapp** [comment]
Alternative: https://github.com/gyunaev/birdtray
