### ISSUE TITLE
Battery indicator does not display after turning off "show time in menu bar"

### ISSUE THREAD

**Issue by nicekiwi** [mate-desktop/mate-indicator-applet#51]
#### Expected behaviour
When un-selecting "Show time in Menu Bar" the battery indicator should hide the time remaining but still show the battery icon.

#### Actual behaviour
When the "Show time in menu bar" option is un-selected the entire indicator is removed.

![Peek 2019-10-27 12-11](https://user-images.githubusercontent.com/738975/67627200-039e0480-f8b4-11e9-8b79-601910ce2644.gif)

#### Steps to reproduce the behaviour
1. Run (or emulate) a laptop on battery. 
2. Click the battery icon and select "Show time in menu bar".
3. Click the battery icon again and de-select "Show time in menu bar".

#### MATE general version
1.22.2

#### Package version
1.22.1-1ubuntu1

#### Linux Distribution
Ubuntu MATE 19.10

#### Link to downstream report of your Distribution
https://bugs.launchpad.net/ubuntu-mate/+bug/1850006

**Comment by Potherca** [comment]
I also encountered this behavior today.

**Comment by flexiondotorg** [comment]
The battery indicator is not part of this project. It is provided by https://github.com/AyatanaIndicators/ayatana-indicator-power
