### ISSUE TITLE
Add ability to load Gtk+3 (possibly also QT?) indicators

### ISSUE THREAD

**Issue by piranna** [mate-desktop/mate-indicator-applet#8]
The indicator applet to show the apps menues doesn't work, showing instead a "no indicators" label. Their equivalent programs for Gnome 2 and gnome-fallback works flawlessly.

**Comment by monsta** [comment]
Now that package is GTK+3 only as of version 1.17, it will load only GTK+3 indicators.

**Comment by h4tr3d** [comment]
@monsta what about Qt indicators?

**Comment by monsta** [comment]
I'm not sure this is possible at all.
